Feature/next lap invalidation
Wesley1041/wes-timing-system-4 pull request #5
Opened 2023-10-16 22:13 UTC by jamburger71

New code changes to allow for next lap invalidation from CC blocks, using ROBLOX attribute values.

Requires the starter CC block to be updated with the Boolean "InvalidsNextLap" attribute to function.

2023-10-17 16:25 UTC, Wesley1041 requested changes
Looks good, but needs a few tweaks before it can be approved. The main thing is that the new feature should be mentioned in the readme.

Can you also update the version number in the readme to 1.1? In the future I think there should be a develop branch.

2023-10-17 16:25 UTC, Wesley1041 commented on src/StarterGui/WesTimingGui/TimingLocalScript/PlayerBehaviourHandler.lua
> +        local nextLapInvalid = part:GetAttribute("InvalidsNextLap")
Can you expand `README.lua` with an explanation on how to do this? This feature should be known from the readme.

2023-10-17 16:27 UTC, jamburger71 commented on src/StarterGui/WesTimingGui/TimingLocalScript/TimingKeeperService.lua
> +        _popupService:NewPopup("CURRENT LAP INVALIDATED BY PREVIOUS LAP CORNER CUT", Color3.fromRGB(170, 41, 41), 300)
I copied the colour from the already existing popup for CCs - should I change that one too?

2023-10-17 16:28 UTC, Wesley1041 commented on src/StarterGui/WesTimingGui/TimingLocalScript/PlayerBehaviourHandler.lua
> +            _keeperService:AddNextLapCut()
This is going to trigger the prompt twice. Once for a regular CC and one for the next lap CC

2023-10-17 16:28 UTC, Wesley1041 commented on src/StarterGui/WesTimingGui/TimingLocalScript/TimingKeeperService.lua
> +        _popupService:NewPopup("NEXT LAP INVALIDATED", Color3.fromRGB(170, 41, 41), 300)
Hardcoded Color3 again

2023-10-18 17:41 UTC, Wesley1041 commented
Line 24 of PopupService.lua is triggering the following error: 
`Unable to assign property BackgroundColor3. Color3 expected, got nil`

This happens when you cross the line after you have a supposed invalid lap. The lap still gets added as new best lap, even though your last lap will be displayed in red.
![image](https://github.com/Wesley1041/wes-timing-system-4/assets/45420192/e5c885fd-5b2a-4bcf-af27-dcbe52497155)

2023-10-18 18:14 UTC, Wesley1041 approved these changes

2023-10-18 18:15 UTC, merged